<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/dist/echarts.min.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/dist/extension/dataTool.min.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/china.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/henan.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/beijing.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/anhui.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/aomen.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/chongqing.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/fujian.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/gansu.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/guangdong.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/guangxi.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/guizhou.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/hainan.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/hebei.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/heilongjiang.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/hubei.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/hunan.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/jiangsu.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/jiangxi.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/jilin.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/liaoning.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/neimenggu.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/ningxia.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/qinghai.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/shandong.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/shanghai.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/shanxi.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/shanxi1.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/sichuan.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/taiwan.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/tianjin.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/xianggang.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/xinjiang.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/xizang.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/yunnan.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/province/zhejiang.js"></script>
<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/dist/extension/bmap.min.js"></script>

<script type="text/javascript" src="${ctxStatic}/echarts3.5.3/map/js/area.js"></script>